apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager
  namespace: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app.component: prometheus
    app.name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels: 
       app.component: prometheus
       app.name: alertmanager
  template:
    metadata:
      labels:
         k8s-app: alertmanager
         app.component: prometheus
         app.name: alertmanager
    spec:
      containers:
        - name: alertmanager
          image:  m.docker-registry.ir/prom/alertmanager:latest
          imagePullPolicy: IfNotPresent
          args:
            - --config.file=/etc/config/alertmanager.yml
            - --storage.path=/alertmanager
            - --data.retention=120h
            - --web.listen-address=:9093
            - --log.level=debug
          ports:
            - containerPort: 9093
              name: http
          readinessProbe:
            httpGet:
              path: /#/status
              port: 9093
            initialDelaySeconds: 10
            timeoutSeconds: 10
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: alertmanager-data
              mountPath: "/alertmanager"
            - name: templates-volume
              mountPath: /etc/alertmanager-templates
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager-config
        - name: templates-volume
          hostPath:
            path: /alertmanager-templates

        - name: alertmanager-data
          emptyDir: {}