apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    app: prometheus
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: false
      name: prometheus
      type: prometheus
      url: http://prometheus.monitoring.svc:9090
      version: 1
